#!/bin/bash
## Indicar cuantos archivos ocultos, cuantos ficheros ordinarios y cuantos subdirectorios tiene un directorio	

lista=`ls -aR`
num=1
for elemento in $lista; do
	echo "$num. $elemento"
	num=$[ num + 1 ]
done
echo "En total hay $num elementos"

